'use strict';
const width = 34;
const height = 69;
const area = width * height;
console.log('Value of area: ', area);
console.log('Type of area: ', typeof area);
const bill = 6.99;
const payment = 10;
const change = payment - bill;
console.log('Value of change: ', change);
console.log('Type of change: ', typeof change);
const quizzes = 75;
const midterm = 85;
const final = 95;
const grade = (quizzes + midterm + final) / 3;
console.log('Value of grade: ', grade);
console.log('Type of grade: ', typeof grade);
const firstName = 'Nader';
const lastName = 'Motamedi';
const fullName = firstName + ' ' + lastName;
console.log('Value of fullName: ', fullName);
console.log('Type of fullName: ', typeof fullName);
const pH = 13;
const isAcidic = pH < 7;
console.log('Value of isAcidic: ', isAcidic);
console.log('Type of isAcidic: ', typeof isAcidic);
const headCount = 275;
const isSparta = headCount === 300;
console.log('Value of isSparta: ', isSparta);
console.log('Type of isSparta: ', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('Value of motto: ', motto);
console.log('Type of motto: ', typeof motto);
